rpm.go, tar_test.go
Before this change, we required our users to input files in the right
alphabetical sorting, in order to be able to process the files on the
fly. But this complicates the interfaces a lot for a memory optimization
that is irrelevant for most cases.
After this change we'll simply collect the files to a map.
=> Allow any order on input.

BUILD.bazel, def.bzl, rpm.go, testdata/content1.txt
A very basic bazel rule to create rpm files.
=> minimal bazel rule for pkg_tar2rpm

.travis.yml
(This only runs the golang tests, not the bazel ones yet)
=> Add travis build for go

cmd/rpmsample/main.go, header.go, rpm.go, tags.go, tar.go
Based on findings from golangci
=> Fix lint errors: mostly unused vars and unchecked errors.

.travis.yml, BUILD.bazel, WORKSPACE, go.mod, go.sum, testdata/golden_ls.txt
Updated the dependencies, with the resulting changes:
- container_image now expects the legacy run behavior flag for each
image
- The tar default timestamp chnaged from 1970 to 2000: bazelbuild/bazel/pull/7276
=> update deps for go and bazel, and update tests

.travis.yml, BUILD.bazel, WORKSPACE, cmd/tar2rpm/main.go, def.bzl, docker_tests.sh, go.mod, go.sum, rpm.go, tags.go, testdata/golden_ls.txt, testdata/golden_preinst.txt
Add scriptlets to the library, tar2rpm, and bazel definition.
Should fix #12 albeit with a slightly different API, because of the way
the scriptlets are defined in rpm, where each scriptlet has its own tag
number and prog tag (The prog tags are required, and seem to always be
`/bin/sh`)
Notice that it is chained to pull request #13 so only the second commit is relevant
=> Add prein and other scriptlets to the library

BUILD.bazel, cmd/tar2rpm/main.go, rpm.go, sense.go, sense_test.go, tags.go
feat: add relation fields
* provides
* obsoletes
* suggests
* recommends
* requires
* conflicts
=> feat: add relation fields

example_bazel/BUILD.bazel, example_bazel/WORKSPACE, example_bazel/diff_test.sh, example_bazel/testing.bzl
1. Improve docker testing by templatizing and separating them.
Using a bzl rule we create a test unit for each cmd.
2. Add a fedora image to the tests and see it fail without nodigest
@djgilcrease reported in #24 that fedora installations currently fail
without passing in nodigest. That does seems to be true. I have
added a test case, that currently passes, but only because of the
`--nodigest` flag. Then as part of #24 we can modify the testcase
to omit the flag.
=> Better docker testing

example_bazel/BUILD.bazel, rpm.go, tags.go
Add the payload digest so that on fedora you do not need to install the rpm with the `--nodigest` flags
Before change
```
$ rpm -Kv test.rpm
test.rpm:
Header SHA256 digest: OK
Payload SHA256 digest: NOTFOUND
MD5 digest: NOTFOUND
```
After Changes
```
$ rpm -Kv test.rpm
test.rpm:
Header SHA256 digest: OK
Payload SHA256 digest: OK
```
=> Add the payload digest

cmd/tar2rpm/main.go, rpm.go, tags.go
according to [this](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-package-structure.html), both are required tags and we are not setting them...
refs https://github.com/goreleaser/goreleaser/issues/1229
=> feat: add description, summary, build time and build host tags

header.go, header_test.go, rpm.go, sense.go
AddCustomTag and AddCustomSig Add OR OVERWRITE tags in the index or
signature. This means that a user can add a tag we don't know about,
or overwrite one we don't usually allow to change. This is a major
footgun, because users can break their rpms, but so what.
Also exposed IndexEntry, and IndexEntry creating methods, one for each
type. (yay generics :( ). This allows safe compile time checking of
input types, but does add some bookchecking for the coder.
Note that tags are saved in a separate map and added after adding our
own tags, but before serializing to bytes. That way the users can add
tags whenever they want.
Fixes #29
=> Allow users to write custom index entries.

rpm.go, rpm_test.go
We had bad logic to deduce symlinks. This caused us to think
files with modes such as 0100644 are symlinks. All this change
does is properly compare the bits.
Fixes #49
=> Handle tar filemodes that overllap with 0120000

cmd/rpmsample/main.go, example_bazel/BUILD.bazel, rpm.go, tags.go
This allows library callers to give us a gpg signing function, which
will be used to sign the contents. The callers can create the signature
however way they want, for example by using golang's openpgp package
or by forking out to gpg. This mostly depends on managing the secret
material. If they want to use the user's keys I guess forking to gpg
is not too bad.
The test is not great: rpmsample was modified to add a signature, which
basically returns the same bytes all the time. This does not actually
validate if rpm based distros accept the key.
=> add pgp signing interface.

rpm.go, tags.go
fixes: https://github.com/goreleaser/nfpm/issues/265
It looks like yum & dnf try to verify the header signature as well even if it is not signed when pulling the rpm from a repo, but not when it is a local file.
=> fix: ensure the rpm signature is properly validated

cmd/rpmsample/main.go, example_bazel/BUILD.bazel
Since #53 our tests are broken, because centos refuses to work with an unverifyable signed header. So we add a flag to sign only in the relevant test, and there use the nosignature flag to avoid centos trying to validate the signature.
This is another reminder that we must fix out CI testing soon.
=> Fix tests by conditionally signing.

BUILD.bazel
This make the repo compatible with --incompatible_disallow_empty_glob
Discovered while using bazelisk `--migrate` option.
=> Make repo compatible with --incompatible_disallow_empty_glob

rpm.go, tags.go
This PR adds %pretrans and %posttrans scriptlets to rpm pkg. 
pretrans and posttrans are run at start and end of a transaction.
On upgrade, the scripts are run in the following order:
1. %pretrans of new package
2. %pre of new package
(package install)
3. %post of new package
4. %preun of old package
5. (removal of old package)
6. %postun of old package
7. %posttrans of new package
=> added %pretrans %posttrans scriptlets

def.bzl
This allows `arch` and `packager` fields to be specified in a `pkg_tar2rpm` rule
=> fields: Add arch and packager fields

BUILD.bazel, deps.bzl, go.mod, go.sum, rpm.go, rpm_test.go
This PR closes #66 by adding support for `zstd` compression. It also allows users to optionally specify the compression level for `gzip` (`gzip:-2` up to `gzip:9`) and `zstd` (`zstd:default`, `zstd:fastest`, `zstd:better`, `zstd:best`, `zstd:17`). It also contains a test for the compression configuration.
I can also add `bzip2` such that this PR can supersede #67 if you want.
=> feat: zstd compression and compressor levels

cmd/rpmsample/main.go, cmd/tar2rpm/main.go, def.bzl, example_bazel/BUILD.bazel, example_bazel/WORKSPACE, example_bazel/dir_allowlist.txt, rpm.go, rpm_test.go, tar.go
Users reported issues with installing rpms that have directories from the core filesystem (such as /etc/, /var/, etc). This change adds the option in `tar2rpm` and in the bazel rules, to only include certain directories. This talks about the directory itself, the content is always included.
Fixes #62
=> Allowlist for directories

def.bzl, example_bazel/testing.bzl
This is apparently how it's done these days. I could not find good docs or announcements, except for this: https://bazel.build/reference/command-line-reference#flag--incompatible_disable_starlark_host_transitions
But I did get a request from a Googler to change this.
=> bazel: replace cfg=host with cfg=exec.

BUILD.bazel, deps.bzl, go.mod, go.sum, header.go, rpm.go, tar.go
nfpm uses errors.Is (since goreleaser/nfpm#630) and I want to undo the fork. Also updated the minimal go version (since this was introduced in 1.13)
=> Use modern go error wrapping instead of errors.Wrap.

rpm.go, tags.go
The `verifyscript` tag is used to add scriptlets for RPM to execute when `rpm -V` is run to enable validation beyond the default file verification.
=> feat: add support for verifyscript tag

rpm.go, rpm_test.go
Packager, vendor, URL, and Epoch are being added to the headers even if they have no value and are not required.
This PR moves them to pointers, and add them if they are non-null values.
Could also not add them if they have their default value, which would not break anyone using the lib, but might be less clear, especially if someone wants to set epoch to 0, for example...
refs https://github.com/goreleaser/nfpm/issues/619
=> fix: handle packager, vendor and others

README.md, cmd/tar2rpm/main.go
When no filenames are given the informative message
"tar2pm: reading tar content from stdin, writing rpm data to stdout."
is printed to stderr. This can be suppressed by explicitly
specifying '-' for TARFILE and RPMFILE (if only TAR- or RPMFILE is
given the message reflects that).
Also updated usage() to reflect that, and rename FILE to
TARFILE/RPMFILE.
=> tar2rpm: add filename '-' as an alias for stdin and stdout

example_bazel/MODULE.bazel, example_bazel/MODULE.bazel.lock, example_bazel/diff_test.sh, example_bazel/docker_run.sh, example_bazel/testing.bzl
This handles bazelbuild/rules_python#1169.
Also clean up some other Bazel madness.
It's also progress on #96, with now only 1/4 of the build steps failing.
=> Work around bazel's python_rules root user restriction.
